grafana-secret-key: ENC[AES256_GCM,data:z4M4L8+H9C4gNcq+kXxYlLO5LykmhAx1XBNBCl8emnd2aiw8vxxBqTr0vezDz5zfeKjRq9geeFr+piM1hZ69Tg==,iv:7CCcgjEkvDjnhWzzqXfQN1iUTRGNibnYFx3znv1KB+E=,tag:Xs4YWsbCuee3caRKbQPyzQ==,type:str]
sops:
  age:
    - recipient: age1k49t7ycus0gyw37fl69y3nl3ny7vsy44p5583qs8rx6asdeeqvjqr8jlh4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNnMwUHZIc0UrcFFESTJh
        MEVTK2MvUVFPUFVtWS9PeGZuV2dkNW9naFRvCnlxYlkraGVucnl3bmF0anVCWjBU
        MXpWTVNGTGh5Y3Q1TzVVVjNBRjArMGMKLS0tIGFUc3cySng3QjZ6ODNwOGJ3eXZW
        N0NUWWxqNjdoYW80a2JKQld2RnJ0Z3cKGrk1mEyLTs6jsRJUMZoto4Kp/miJKJ3R
        LVqVnrCY0jjUEOeX3SEaVR43sOe86dQZ6Wb+EOuseE+wgPeDYWUS8w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T11:09:43Z"
  mac: ENC[AES256_GCM,data:n5848eD5VV1iB7caXb4eme3FiIB23CMRLs6ls93CSEvrG6rRGwG+9ch56+NIwBffKRIKugyxAOv9VoJuCLjVk9y9TXl0zvsDqP70YdnrciGg+mb0U19LYlur23QYgC6P2sm2w2asRuVZt0hDOX9zaTFAsM3lEfWLWC/RutLEeok=,iv:Sv4FoffuQqcK5CmSu42LwOPqPtgLHYiDX/SMI0VL6ZI=,tag:DDxWit0cLmeF2xj/g6KgoQ==,type:str]
  pgp:
    - created_at: "2026-02-20T11:09:43Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DA2FdwJLszpkSAQdAcj4ZbVehtYhcMf7d5BWXMmTd/BnBgOZnoeS5m9TfvD8w
        4XRokhc105K8UUWl0pWe1Uaa301l0Se9l2yS1alOKq9xHGMPa3nZrnJVnoYLYqPb
        0l4B8j0hhthbBC6OgQNRXmwzW1v5MIOdUkC0HHIM6OYBuyJ2Av9+XYYlWupmc04C
        S2PigFlUusEL7YZSOk3MZGoXIwclJRjizyCjJRo3a0hA/zBVZbdCD0fkeyAM3hcw
        =QJtc
        -----END PGP MESSAGE-----
      fp: 20D22783FF50D18568CF617303615DC092ECCE99
  unencrypted_suffix: _unencrypted
  version: 3.11.0
